### PR TITLE
add zoom slider

### PR DESCRIPTION
**Pull request by fippo**
The Logitech Brio 4k only supports Pan/Tilt when zoomed in according to
  https://support.logitech.com/en_ch/article/Pan-and-tilt-with-the-BRIO-webcam?product=a0q3100000BNfaFAAT

Adding a zoom slider makes this work.

### CODE REVIEW

**Comment by fippo** [comment]
(this is somewhat confusing... maybe adding a note that some cameras may require zoom would help?)

**Comment by riju** [comment]
Thanks for the PR!  Yes a note should be useful. We can add a README in the samples/panTilt folder.

**Comment by fippo** [comment]
Done (and squashed). Added a link to the readme to the html too, see https://github.com/fippo/WebCamera/tree/zoom/samples/panTilt for the rendered version

**Comment by riju** [comment]
Thanks !

**Pull request merged**
